language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
script: date | sha1sum | curl -F 'sprunge=<-' http://sprunge.us
cache:
  directories:
    - node_modules
sudo: true
after_success:
  - script: echo SUCCESS
  - sh ./deploy.sh
